name: SimplySpawn
main: com.minetexas.simplyspawn.SimplySpawn
version: '0.3'
authors: [ataranlen, RainbowSpeedy]
description: Random Spawn.
api-version: '1.16'
commands:
  rs_setspawn:
    description: Sets the server spawn point to your current position.
    aliases: setspawn
    usage: /<command>
  rs_spawn:
    description: Warps you to the location of the spawn point.
    aliases: spawn
    usage: /<command>
  rs_rspawn:
    description: Randomly sends you around the world.
    aliases: rspawn
    usage: /<command>
  bed:
    description: Checks if your bed spawn is valid.
    aliases: bed
    usage: /<command>
  getbed:
    description: Checks for the coordinates of another player''s bed spawn point.
    aliases: getbed
    usage: /<command>
permissions:
  rssetspawn.spawn:
    description: 'Permission to use /spawn'
    default: true
  rssetspawn.rspawn:
    description: 'Permission to use /rspawn'
    default: true
  rssetspawn.setspawn:
    description: 'Permission to use /setspawn'
    default: op
  rssetspawn.bed:
    description: 'Permission to use /bed'
    default: op
  rssetspawn.getbed:
    description: 'Permission to use /getbed'
    default: op
  rssetspawn.reload:
    description: 'Permission to use /ssreload'
    default: op